server:
  port: 8315

spring:
  application:
    name: youzan-data-web
  profiles:
    active: dev
  
#mybatis:
  #映射文件所在路径
  #mapper-locations: classpath*:mapper/*.xml
  #pojo类所在包路径
  #type-aliases-package: com.longsys.bi.api.bean
  


quartz: 
  #spring 定时任务线程池大小
  threadPool: 15
  
  